DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MyHengDaProject/urls.py
from django.contrib import admin
from django.urls import path, include
from homeApp.views import home
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('aboutApp/', include('aboutApp.urls')),
    path('contactApp/', include('contactApp.urls')),
    path('newsApp/', include('newsApp.urls')),
    path('productsApp/', include('productsApp.urls')),
    path('serviceApp/', include('serviceApp.urls')),
    path('scienceApp/', include('scienceApp.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('search/', include('haystack.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

aboutApp/urls.py
# 企业概况
# path('survey/', survey, name= 'survey')
from django.urls import path
from . import views

app_name = 'aboutApp'

urlpatterns = [
    path('survey/', views.survey, name='survey'),
    path('honor/', views.honor, name='honor'),
]

contactApp/urls.py
from django.urls import path
from . import views

app_name = 'contactApp'

urlpatterns = [
    path('contact/', views.contact, name='contact'),  # 欢迎咨询
    path('recruit/', views.recruit, name='recruit'),  # 加入恒达
]

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    # path('company/', views.company, name='company'),  # 企业要闻
    # path('industry/', views.industry, name='industry'),  # 行业新闻
    # path('notice/', views.notice, name='notice'),  # 通知公告
    path('news/<str:newName>/', views.news, name='news'),  # 名为news的路由，调用views.py中的news函数
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search'),

]

scienceApp/urls.py
from django.urls import path
from .import views


app_name='scienceApp'


urlpatterns=[
    path('science/',views.science,name='science'), #科研基地
]

serviceApp/urls.py
from django.urls import path
from . import views

app_name = 'serviceApp'

urlpatterns = [
    path('download/', views.download, name='download'),  # 资料下载
    path('platform/', views.platform, name='platform'),  # 人脸识别开放平台
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
    path('facedetect/', views.facedetect, name='facedetect'),  # 人脸检测api
    path('facedetectDemo/', views.facedetectDemo, name='facedetectDemo'),
    path('search/', views.search, name='search'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>恒达科技|{% block title %} {% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- 顶部图片 -->
<div class="container top">
    <div class="row">
        <div class="col-md-6">
            <a>
                <img class="img-responsive" src="{% static 'img/logo.jpg' %}">
            </a>
        </div>
        <div class="col-md-3 hidden-xs">
            <a class="phone ant">
                <span class="glyphicon glyphicon-phone"></span>电话：400 1111 0000 &nbsp;&nbsp;
            </a>
        </div>
        <div class="col-md-3 hidden-xs">
            <a class="mail ant">
                <span class="glyphicon glyphicon-envelope"></span>邮箱：hengda@126.com
            </a>
        </div>
    </div>
</div>

<!--导航栏具体内容-->
{#<nnavbar-defaultav class="navbar " role="navigation">#}

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example" aria-expanded="false">
                <span>导航栏</span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example">
            <ul class="nav navbar-nav" style="width:100%;">
                <li class="nav-top" id="home">
                    <a href="{% url 'home' %}">首页</a>
                </li>
                <li class="dropdown nav-top">
                    <a href="#" class="dropdown-toggle on" data-toggle="dropdown">公司简介</a>
                    <ul class="dropdown-menu" id="about">
                        <li><a href="{% url 'aboutApp:survey' %}">企业概况</a></li>
                        <li><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></li>
                    </ul>
                </li>
                <li class="dropdown nav-top">
                    <a href="#" class="dropdown-toggle on" data-toggle="dropdown">新闻动态</a>
                    <ul class="dropdown-menu" id="news">
{#                        <li><a href="{% url 'newsApp:company' %}">企业要闻</a></li>#}
{#                        <li><a href="{% url 'newsApp:industry' %}">行业新闻</a></li>#}
{#                        <li><a href="{% url 'newsApp:notice' %}">通知公告</a></li>#}
                        <li><a href="{% url 'newsApp:news' 'company' %}">公司要闻</a></li>
                        <li><a href="{% url 'newsApp:news' 'industry'%}">行业新闻</a></li>
                        <li><a href="{% url 'newsApp:news' 'notice'%}">通知公告</a></li>

                    </ul>
                </li>
                <li class="dropdown nav-top" id="products">
                    <a href="#" class="dropdown-toggle on" data-toggle="dropdown">产品中心</a>
                    <ul class="dropdown-menu">
{#                        <li><a href="{% url 'productsApp:robot' %}">家用机器人</a></li>#}
{#                        <li><a href="{% url 'productsApp:monitoring' %}">智能监控</a></li>#}
{#                        <li><a href="{% url 'productsApp:face' %}">人脸识别解决方案</a></li>#}
                        <li><a href="{% url 'productsApp:products' 'robot' %}">家用机器人</a></li>
                        <li><a href="{% url 'productsApp:products' 'monitor' %}">智能监控</a></li>
                        <li><a href="{% url 'productsApp:products' 'face' %}">人脸识别解决方案</a></li>
                    </ul>
                </li>
                <li class="dropdown nav-top" id="service">
                    <a href="#" class="dropdown-toggle on" data-toggle="dropdown">服务支持</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'serviceApp:download' %}">资料下载</a></li>
                        <li><a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a></li>
                    </ul>
                </li>
                <li class="nav-top" id="science">
                    <a href="{% url 'scienceApp:science' %}">科研基地</a>
                </li>
                <li class="dropdown nav-top">
                    <a href="#" class="dropdown-toggle on" data-toggle="dropdown">人才招聘</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></li>
                        <li><a href="{% url 'contactApp:recruit' %}">加入恒达</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    {#</nnavbar-defaultav>#}
</nav>

<!-- 放具体内容的地方, 在这个地方做一个标记, 之后其他HTML代码会插入到这个位置 -->
{% block content%}
{% endblock %}

<!-- 页面页脚的内容 -->
<div class="container web-footer">
    <!-- 站点地图 -->
    <div class="row" id="map-footer">
        <div class="col-md-2">
            <dl>
                <dt>公司简介</dt>
                <dd><a href="{% url 'aboutApp:survey' %}">企业概况</a></dd>
                <dd><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>产品中心</dt>
{#                <dd><a href="{% url 'productsApp:robot' %}">家用机器人</a></dd>#}
{#                <dd><a href="{% url 'productsApp:monitoring' %}">智能监控</a></dd>#}
{#                <dd><a href="{% url 'productsApp:face' %}">人脸识别解决方案</a></dd>#}
                <dd><a href="{% url 'productsApp:products' 'robot' %}">家用机器人</a></dd>
                <dd><a href="{% url 'productsApp:products' 'monitor' %}">智能监控</a></dd>
                <dd><a href="{% url 'productsApp:products' 'face' %}">人脸识别解决方案</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>服务支持</dt>
                <dd><a href="{% url 'serviceApp:download' %}">资料下载</a></dd>
                <dd><a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a></dd>
            </dl>
        </div>
        <div class="col-md-2">
            <dl>
                <dt>人才招聘</dt>
                <dd><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></dd>
                <dd><a href="{% url 'contactApp:recruit' %}">加入恒达</a></dd>
            </dl>
        </div>
        <div class="col-md-4" id="wx">
            <p>扫描二维码，关注我们</p>
            <img class="qrimg" src="{% static 'img/qr.png' %}" alt="wx">
            <p>客服热线：<b style="font-size:20px">400 111 2222</b></p>
        </div>
    </div>
    <!-- 版权 -->
    <div class="row" id="patent-footer">
        <p> © 2019 Python Web企业门户网站开发示例 版权所有 | 苏ICP备19006378号 </p>
    </div>
</div>

</body>

<!--一些js控制代码-->
<script>
    $(function () {
        $(".dropdown").mouseover(function () {
            $(this).addClass("open");
        });
        $(".dropdown").mouseleave(function () {
            $(this).removeClass("open")
        });
    })
</script>

<script>
    $('#{{ active_menu }}').addClass("active")
</script>

{#base.html添加模板变量sub_menu,   某个元素会添加active类，  需要从后台传值给sub_menu#}
<script>
    $('#{{ sub_menu }}').addClass("active")
</script>



</html>